# Generated by Django 5.2.4 on 2025-07-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=100)),
            ],
        ),
    ]
