# Generated by Django 5.2.4 on 2025-07-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pro_builder',
        ),
    ]
