# Generated by Django 5.2.4 on 2025-07-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_delete_test_remove_user_is_pro_builder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
